### ISSUE TITLE
App doesn't boot

### ISSUE THREAD

**Issue by screeper** [athena-logistics/athena-rn#102]
App does not boot (start screen freezes).

Version: 1.5.1
Tried with multiple Android phones.

**Comment by maennchen** [comment]
@screeper Should be fixed with 7ae0b13c46f45cbf3c6c1a22b98cd8d9ce658f46 and released to the Apple & Play Store as `1.5.2`. Can you check?

**Comment by screeper** [comment]
Works fine. Thanks :)
